name: Create kitchen every weekday

on:
  schedule:
    # Triggers At 06:00 on every day-of-week from Monday through Friday
    - cron:  '0 6 * * 1-5'


jobs:  
  # Apply Infrastructure configurations when a issue is labelled as "create".
  create-kitchen:
    name: Create kitchen resources
    uses: ./.github/workflows/terraform-create.template.yaml
    with:      
      secrets_keys_list: 'terraformApiToken'
    secrets:
      key_vault_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      key_vault_name: ${{ secrets.AZURE_KEY_VAULT_NAME }}